### ISSUE TITLE
[swm-emacs] swm-emacs doesn't load (shepherd needed)

### ISSUE THREAD

**Issue by dmb2** [stumpwm/stumpwm-contrib#105]
Someone should complete/update/fix the port from deep space window manager.  If this module doesn't have a shepherd by the next release it will be removed.

**Comment by PuercoPop** [comment]
Is there any issue besides the missing `cl-fad` dependency?

**Comment by marcowahl** [comment]
If you don't find someone else I'd happily take the responsibility for the module.  I even am a user of the module!
