### ISSUE TITLE
modeline/maildir broken with new faster mode-line

### ISSUE THREAD

**Issue by brandoninvergo** [stumpwm/stumpwm-contrib#126]
StumpWM issue/pull [#577](https://github.com/stumpwm/stumpwm/pull/577) broke the maildir modeline module. Stump effectively freezes as soon as the modeline loads.

If you remove the timer code (maildir.lisp lines 83-85 plus the earlier definitions), it works fine but of course then the maildir recounts need to be triggered manually.  That's fine for me because that's already what I was doing in my own customization of the code. However I'm not sure what would be the best way to properly fix it for everyone, hence just a simple bug report and not a full pull request.

**Comment by PuercoPop** [comment]
I haven't looked into this, but it could be a lock contention issue. Could you see if adding a time to to run-with-timer fixes the issue?
http://www.sbcl.org/manual/#Mutex-Support

**Comment by brandoninvergo** [comment]
Just to make sure I understand what you mean: are you asking for me to try changing line 85 of maildir.lisp from:
    (run-with-timer 0 *maildir-update-time* #'update-maildir-infos)
to something like:
    (run-with-timer 60 *maildir-update-time* #'update-maildir-infos)
?

**Comment by PuercoPop** [comment]
@brandoninvergo Sorry for not being more clear, no. I'm was talking code implementation of [`run-with-timer`](https://github.com/stumpwm/stumpwm/blob/6115981c378ec46f26e97bdf7c53766883aa03a3/timers.lisp#L64). To add a timeout to the trying to acquire the lock. So something like

(sb-thread:with-mutex (*timer-list-lock* :timeout 1)
  ....)

**Comment by brandoninvergo** [comment]
Ok thanks. I'm sorry I haven't had a chance to try it yet.

However, I'm finding that on a different system with the same configuration, I'm getting random lock-ups even with the maildir modeline configuration removed.  So, it doesn't seem to be isolated to just that module.  Unfortunately this other system is my work computer, where I don't really have the time or inclination to dig into it.

**Comment by jorams** [comment]
stumpwm/stumpwm#577 has now been reverted by stumpwm/stumpwm#599. That should fix this issue.
