### ISSUE TITLE
XEMBED:*TIMESTAMP* is bound to nil when initialzing StumpTray. Expecting an (UNSIGNED-BYTE 32)

### ISSUE THREAD

**Issue by YorkZ** [stumpwm/stumpwm-contrib#142]
After upgrading my `archlinux` system with:

    sudo pacman -Syyu

and re-installing the `StumpWM` from `AUR`, the `stumptray` no longer works. In my `~/.stumpwm.d/init.lisp` file, I have the following lines:

```
(load-module "stumptray")
(stumptray::stumptray)
```
If I remove the line:

    (stumptray::stumptray)
    
The entire `init.lisp` file would be evaluated successfully, but with no system tray, of course. Then if I manually evaluate the above line, I got the following errors:

```
The value
  NIL
is not of type
  (UNSIGNED-BYTE 32)
   [Condition of type TYPE-ERROR]

Restarts:
 0: [RETRY] Retry SLIME interactive evaluation request.
 1: [*ABORT] Return to SLIME's top level.
 2: [ABORT] abort thread (#<THREAD "worker" RUNNING {1005FDF353}>)

Backtrace:
  0: (XLIB::WRITE-VECTOR-CARD32 #<XLIB:DISPLAY :0 (The X.Org Foundation R12005000)> 24 #(NIL 502 8389191 0 0) 0 5)
  1: ((FLET SB-THREAD::WITH-RECURSIVE-LOCK-THUNK :IN XLIB:SEND-EVENT))
  2: ((FLET "WITHOUT-INTERRUPTS-BODY-29" :IN SB-THREAD::CALL-WITH-RECURSIVE-LOCK))
  3: (SB-THREAD::CALL-WITH-RECURSIVE-LOCK #<CLOSURE (FLET SB-THREAD::WITH-RECURSIVE-LOCK-THUNK :IN XLIB:SEND-EVENT) {7F0AA63BDDFB}> #<SB-THREAD:MUTEX "CLX Buffer Lock" owner: #<SB-THREAD:THREAD "worker" RU..
  4: (XLIB:SEND-EVENT #<XLIB:WINDOW :0 6FA> :CLIENT-MESSAGE 131072 :WINDOW #<XLIB:WINDOW :0 6FA> :TYPE :MANAGER :FORMAT 32 :DATA #(NIL 502 8389191 0 0) :PROPAGATE-P NIL)
  5: (XLIB:SEND-EVENT #<XLIB:WINDOW :0 6FA> :CLIENT-MESSAGE 131072 :WINDOW #<XLIB:WINDOW :0 6FA> :TYPE :MANAGER :FORMAT 32 :DATA #(NIL 502 8389191 0 0) :PROPAGATE-P NIL) [more]
  6: (STUMPTRAY::TRAY-INIT #S(STUMPTRAY::TRAY :WIN #<XLIB:WINDOW stumpwm/stumpwm#1=:0 800245> :SOWIN #<XLIB:WINDOW stumpwm/stumpwm#1#:0 800247> :FPWIN #<XLIB:WINDOW stumpwm/stumpwm#1#:0 800246> :VIWIN #<XLIB:WINDOW stumpwm/stumpwm#1#:0 800248> :HIWIN #<XLIB:WINDOW ..
  7: (STUMPTRAY:STUMPTRAY)
  8: (SB-INT:SIMPLE-EVAL-IN-LEXENV (STUMPTRAY:STUMPTRAY) #<NULL-LEXENV>)
  9: (EVAL (STUMPTRAY:STUMPTRAY))
 10: ((LAMBDA NIL :IN SWANK:INTERACTIVE-EVAL))
 11: (SWANK::CALL-WITH-RETRY-RESTART "Retry SLIME interactive evaluation request." #<CLOSURE (LAMBDA NIL :IN SWANK:INTERACTIVE-EVAL) {10074C788B}>)
 12: (SWANK::CALL-WITH-BUFFER-SYNTAX NIL #<CLOSURE (LAMBDA NIL :IN SWANK:INTERACTIVE-EVAL) {10074C786B}>)
 13: (SB-INT:SIMPLE-EVAL-IN-LEXENV (SWANK:INTERACTIVE-EVAL "(stumptray::stumptray)") #<NULL-LEXENV>)
 14: (EVAL (SWANK:INTERACTIVE-EVAL "(stumptray::stumptray)"))
 15: (SWANK:EVAL-FOR-EMACS (SWANK:INTERACTIVE-EVAL "(stumptray::stumptray)") ":stumpwm" 11)
 16: ((LAMBDA NIL :IN SWANK::SPAWN-WORKER-THREAD))
 17: (SWANK/SBCL::CALL-WITH-BREAK-HOOK #<FUNCTION SWANK:SWANK-DEBUGGER-HOOK> #<FUNCTION (LAMBDA NIL :IN SWANK::SPAWN-WORKER-THREAD) {5363983B}>)
 18: ((FLET SWANK/BACKEND:CALL-WITH-DEBUGGER-HOOK :IN "/home/yzhao/quicklisp/local-projects/slime/swank/sbcl.lisp") #<FUNCTION SWANK:SWANK-DEBUGGER-HOOK> #<FUNCTION (LAMBDA NIL :IN SWANK::SPAWN-WORKER-THRE..
 19: (SWANK::CALL-WITH-BINDINGS ((*STANDARD-INPUT* . stumpwm/stumpwm#1=#<SWANK/GRAY::SLIME-INPUT-STREAM {10040E81A3}>) (*STANDARD-OUTPUT* . stumpwm/stumpwm#2=#<SWANK/GRAY::SLIME-OUTPUT-STREAM {10040E8233}>) (*TRACE-OUTPUT* . stumpwm/stumpwm#2#) (*ERR..
 20: ((LAMBDA NIL :IN SWANK::SPAWN-WORKER-THREAD))
 21: ((FLET SB-UNIX::BODY :IN SB-THREAD::INITIAL-THREAD-FUNCTION-TRAMPOLINE))
 22: ((FLET "WITHOUT-INTERRUPTS-BODY-4" :IN SB-THREAD::INITIAL-THREAD-FUNCTION-TRAMPOLINE))
 23: ((FLET SB-THREAD::WITH-MUTEX-THUNK :IN SB-THREAD::INITIAL-THREAD-FUNCTION-TRAMPOLINE))
 24: ((FLET "WITHOUT-INTERRUPTS-BODY-1" :IN SB-THREAD::CALL-WITH-MUTEX))
 25: (SB-THREAD::CALL-WITH-MUTEX #<CLOSURE (FLET SB-THREAD::WITH-MUTEX-THUNK :IN SB-THREAD::INITIAL-THREAD-FUNCTION-TRAMPOLINE) {7F0AA63BED7B}> #<SB-THREAD:MUTEX "thread result lock" owner: #<SB-THREAD:THR..
 26: (SB-THREAD::INITIAL-THREAD-FUNCTION-TRAMPOLINE #<SB-THREAD:THREAD "worker" RUNNING {1005FDF353}> NIL #<CLOSURE (LAMBDA NIL :IN SWANK::SPAWN-WORKER-THREAD) {1005FDF2FB}> NIL)
 27: ("foreign function: call_into_lisp")
 28: ("foreign function: new_thread_trampoline")
```
Please help, thanks in advance!

P.S. stumpwm was upgraded from 18.11.61.g4653857-1 to 18.11.81.gf6966ca-1

**Comment by PuercoPop** [comment]
@YorkZ `update-dist` requires you to specify a distribution, `update-all-dists` doesn't. Although reading the documentation you linked to the recommended way to update would be `(ql:update-dist "quicklisp")`. Given that ne comers are unlikely to have installed a different distribution than the one quicklisp provided there is no meaningful difference between them.

The only quicklisp distribution I'm aware of is the one provided by the [Radiance Web framework](https://shirakumo.github.io/radiance-homepage/#develop) but that is out of scope of installing StumpWM.

The docs you listed are the best documentation of quicklisp I'm aware of. The only command I use occasionally that is not listed there is (ql:register-local-projects) so that documentation should cover you needs. If it doesn't don't hesitate to ask here or over irc.

**Comment by YorkZ** [comment]
Thanks again for your explanation. Hope this issue will get resolved soon.

**Comment by alexanderbarbosa** [comment]
@YorkZ 

Compiling sbcl anew fix stumptray error, but now it wont load notify. newest compiled file is different!

**Comment by YorkZ** [comment]
I just recompiled and installed `StumpWM` a46080, with stump-contrib at a077bf4. Nothing changed!

**Comment by YorkZ** [comment]
I just tried downgrading `stumpwm` to 4653857, and `stumpwm-contrib` to 5124950. But the problem was still exactly the same. The following is my archlinux PKGBUILD file:
```
# Contributor: Chris Dunder <echo Y2R1bmRlckBnbWFpbC5jb20K | base64 -d>
# Contributor: M Rawash <mrawash@gmail.com>
# Contributor: olvar <beren dot olvar (at) gmail dot com>
# Contributor: Andrew Antle <andrew dot antle at gmail dot com>
# Contributor: joyfulgirl <joyfulgirl (at) archlinux.us>
# Contributor: Jonathan Friedman <jonf@gojon.com>
# Maintainer: Stefan Husmann <stefan-husmann@t-online.de>

pkgname=stumpwm-git
_pkgname=stumpwm
pkgver=18.11.61.g4653857
pkgrel=1
pkgdesc="A tiling, keyboard-driven window manager written in common lisp"
arch=('i686' 'x86_64')
url="https://stumpwm.github.io"
license=('GPL2')
conflicts=('stumpwm' 'stumpwm-contrib')
provides=('stumpwm' 'stumpwm-contrib')

source=(${_pkgname}::git+https://github.com/stumpwm/stumpwm#commit=4653857 stumpwm.desktop
        ${_pkgname}-contrib-git::git+https://github.com/stumpwm/stumpwm-contrib#commit=5124950)
md5sums=('SKIP'
         'b5721de9b1cbdb4548d11570a512c5d4'
         'SKIP')

makedepends=('common-lisp' 'cl-asdf' 'clx-git' 'cl-ppcre' 'cl-alexandria')
optdepends=('xorg-xprop: for stumpish (StumpWM Interactive Shell)'
            'rlwrap: for stumpish completion and history'
            'emacs: Edit and eval stumpwm code with M-x stumpwm-mode'
            'alsa-utils: for amixer.lisp (control audio volume)'
            'aumix: for aumix.lisp (control audio volume)'
            'mpd: for mpd.lisp (control the mpd)'
            'surfraw: for surfraw.lisp (surf the Internet)'
            'clx-truetype: for ttf-fonts.lisp (Xft fonts)')

# Binary will not run other
options=('!strip' '!makeflags')  # Thanks to sidereus for pointing this out

pkgver() {
  cd ${_pkgname}
  git describe --long --tags|tr - .
}

_contribdest=/usr/share/stumpwm/contrib

build() {
  cd ${_pkgname}

  autoconf
  ./configure --prefix=/usr --with-module-dir=${_contribdest}
  make
} 

package() {
  cd ${_pkgname}

  make destdir="$pkgdir/" install

  install -Dm 644 sample-stumpwmrc.lisp \
	  ${pkgdir}/usr/share/${_pkgname}/stumpwmrc.sample

  # contrib modules
  install -d "$pkgdir"/${_contribdest}
  cp -dr --no-preserve=ownership ${srcdir}/${_pkgname}-contrib-git/* \
     ${pkgdir}${_contribdest}

  # stumpish
  install -Dm755 "$pkgdir"/${_contribdest}/util/stumpish/stumpish \
	  "$pkgdir"/usr/bin/stumpish

  rm -rf "$pkgdir"/${_contribdest}/util/stumpish

  # emacs mode
  cd "$pkgdir"/${_contribdest}/util/swm-emacs
  install -d "$pkgdir"/usr/share/emacs/site-lisp/
  for _i in *.el 
  do
    install -Dm644 ${_i} "$pkgdir"/usr/share/emacs/site-lisp/${_i}
  done
  install -Dm644 "$srcdir"/stumpwm.desktop "$pkgdir"/usr/share/xsessions/stumpwm.desktop
}
```
I then downgraded by running:
```
makepkg -s
sudo pacman -U stumpwm-git-18.11.61.g4653857-1-x86_64.pkg.tar.xz
```
From my pacman log
```
[2019-08-10 22:50] [ALPM] upgraded sbcl (1.4.16-1 -> 1.5.3-1)
```
I upgraded `sbcl` from 1.4.16-1 to 1.5.3-1, so I will try downgrading my `sbcl`. But before doing so, is there any other suggestions?

**Comment by alexanderbarbosa** [comment]
I dont think your error has anything with sbcl or stumpwm, or even how arch build stumpwm.

It can be fasl files(~/.cache/common-lisp), stumptray depencies update...

**Comment by YorkZ** [comment]
@alexanderbarbosa 

> Compiling sbcl(upstream) anew fix stumptray error!
Could you provide more details, for example, the git repo tag name etc.

> I don't think your error has anything with sbcl or stumpwm, or even how arch builds stumpwm.
I agree those seem to be much less likely the cause. I listed the PKGBUILD file only to make sure no careless mistakes had been made along the way, and also give more details.

> It can be fasl files(~/.cache/common-lisp), stumptray depencies update...
Interesting. There are two directories `sbcl-1.4.16-linux-x64` and `sbcl-1.5.3-linux-x64` under `~/.cache/common-lisp`, I'm studying those to see if there's anything I can try about them. Could you also give me more details?

**Comment by alexanderbarbosa** [comment]
@YorkZ 

- I literally do make once clone sbcl

- Arch is well know for its build scripts, I doubt there is the cause of this issue

- Just remove it all

**Comment by YorkZ** [comment]
Thank you very much @alexanderbarbosa, I'll definitely try installing StupmWM locally instead of installing it system wide because StumpWM is in archlinux AUR, meaning that I have to rebuild and reinstall StumpWM each time if sbcl is upgraded. Now that I have to rebuild it, why not rebuild it locally in the HOME.
However, I still feel more comfortable installing sbcl system wide. I noticed the latest sbcl version is 1.5.5, so I did a full system upgrade which brought sbcl to 1.5.5. I then did the following in order:

1. Rebuilt and re-installed `cl-alexandria`, `clx-git.git`, `cl-ppcre.git` and `aumix` system wide through AUR.
2. Reinstalled `quicklisp` in my HOME, updated all the packages I installed in quicklisp.
3. Rebuilt and reinstalled `stumpwm` and `stumpwm-contrib` from git master, through archlinux AUR

I monitored the directory `~/.cache/common-lisp`, noticed that a new sub-directory called `sbcl-1.5.5-linux-x64` was created. I then checked this directory, and found nothing  unusual. Finally, the original problem was still there, nothing changes.

I think I'm going to downgrade sbcl to see if it addresses the problem.

**Comment by YorkZ** [comment]
After a lot of experimentation, I finally got it back working, so the following was what I tried:

1. sbcl from git master + stumpwm (with contrib) from git master: didn't work
2. sbcl 1.4.16 + stumpwm (with contrib) from git master: didn't work
3. sbcl 1.4.16 + stumpwm from git commit 4653857 + stumpwm contrib from git commit 5124950: didn't work
4. sbcl 1.4.16 + stumpwm (with contrib) archlinux package I built on April 30, 2019: didn't work
5. sbcl 1.4.16 + stumpwm (with contrib) archlinux package I built on April 30, 2019: didn't work + deleting the directory `~/.cache/common-lisp/sbcl-1.4.16-linux-x64`: WORKED!

@alexanderbarbosa Thank you very much for mentioning about the fasl cache. I'll try using sbcl 1.4.16 + stumpwm (with contrib) from git master + deleting the fasl cache.

**Comment by alexanderbarbosa** [comment]
@YorkZ 

Good to know. Time to hack StumpWM, aint? :D

**Comment by YorkZ** [comment]
@alexanderbarbosa, just did two more experiments:

1. sbcl 1.4.16 + stumpwm (with contrib) from git master + deleting fasl cache: didn't work
2. sbcl 1.4.16 + stumpwm from git commit 4653857 + stumpwm contrib from git commit 5124950 + deleting fasl cache: didn't work

While I'm pretty sure the stumpwm commit used in the package I built on Apr. 30 was 4653857, I'm not 100% sure whether the stumpwm contrib commit was 5124950 because this commit was not recorded in the AUR `pkgver`, unfortunately. Any chance to know exactly which commit it was?

**Comment by YorkZ** [comment]
Just tried sbcl 1.4.16 + stumpwm from git commit 4653857 + stumpwm contrib from git commit beac523 + deleting fasl cache, still didn't work.
Any other stumpwm contrib commit to try?
@alexanderbarbosa I'm pretty good at Emacs Lisp, but know very little about common lisp and stumpwm. Can you give me some suggestion as to where I can start if I have to hack StumpWM?

**Comment by alexanderbarbosa** [comment]
@YorkZ 

If you know your way with emacs-lisp, just skim through Paul Graham Ansi Common Lisp and Practical Common LIsp

**Comment by PuercoPop** [comment]
@YorkZ I'm pretty sure the issue you are running into is not due to the version you are running. StumpTray works on only one of my machines and in the other I run into the same issue you report. So you don't need to keep trying different versions.

> I'm pretty good at Emacs Lisp, but know very little about common lisp and stumpwm. Can you give me some suggestion as to where I can start if I have to hack StumpWM?

I'm somewhat certain the issue is in how xembed generates the `CurrentTime` timestamp and that the that the bug is in either xembed or StumpTray.

After setting up Sly (or SLIME if you prefer) you can follow the [instructions in the wiki](https://github.com/stumpwm/stumpwm/wiki/Hacking-StumpWM#emacs) to connect the process running StumpWM to a Sly REPL.

If you want to take a stab at this bug you should at least skim the relevant freedesktop specs to get a sense of how xembed and system trays work.

- https://standards.freedesktop.org/xembed-spec/xembed-spec-latest.html
- https://standards.freedesktop.org/systemtray-spec/systemtray-spec-0.2.html

Besides `#lisp@freenode` which is great for general lisp questions, for StumpWM specific questions `#stumpwm@freenode` may be more helpful.

**Comment by YorkZ** [comment]
This turns out to be a very complicated problem because there are many variables come into play:

1. `sbcl` must be 1.4.16 (or, maybe some version between 1.4.16 and 1.5.3 exclusive)
2. `clx` must be commit 4b9c202 (maybe 3b37000, cf81a5a or 8381835)
3. If condition 1 and 2 hold, `stumpwm` and `stumpwm-contrib` can be the latest (5e1abc5 and a077bf4 respectively at the time of this test). However, even though no errors show up, and the system tray appears, the application `slack` doesn't work properly. I.e., once inside the `slack` window, there's no way to switch to other window except exiting from `slack`.
4. The only combination that "fully works" is: `sbcl` 1.4.16 + clx 4b9c202 + stumpwm 4653857 + stumpwm-contrib 5124950.

Sigh, any idea?

**Comment by YorkZ** [comment]
@PuercoPop Just saw your message, and thank you very much for your help. I'll definitely follow your suggestions once I get some time, but I'm afraid I won't have any time for this in the next two weeks.

**Comment by admich** [comment]
I have the same problem but my experimentation have found that the problem is in clx and not in stumpwm.

The problem have started with the upgrade of quicklisp to version 2019-08-13.

I solved the problem changing clx version using the commit 8381835.

So the problem seems due to commit  bef2661 of clx.

**Comment by admich** [comment]
@YorkZ what is Slack and how install it. I use arch linux.

**Comment by YorkZ** [comment]
@admich Slack is an instant messaging software widely used by many R&D teams. A few teams in our company, for example, use Slack at work to ask questions, exchange ideas and opinions etc. In the team I'm working for (a software and hardware development team), we use Slack extensively, and almost never use email. You can read more about this software an https://en.wikipedia.org/wiki/Slack_(software), and download Slack from https://slack.com/intl/en-ca/downloads/linux.

**Comment by admich** [comment]
I think that I have a solution for the problem due to commit bef2661 of `clx`. This commit enforce some type checking in `clx` and so produce errors but the problem is not in `clx` but in `clx-xembed` that sometimes use a  `nil` value instead of an `(unsigned-int 32)`. I modify clx-xembed in: 

https://github.com/admich/clx-xembed

If you think that my modifications are right I will made a PR on the main repo of `clx-xembed`.

About the `stumpwm` commit 92922d4 I don't have any problem. 

@YorkZ 
I installed `Slack` but without an account I only start the application, I see icon in the systemtray without problem.
The commit change only one function `update-configuration`, try to see with some `(log:error ....` . when it's called and what are the value of `(xlib:drawable-x (window-parent win))` and `(xlib:drawable-x (window-xwin win))` inside the function.

**Comment by YorkZ** [comment]
@admich Thank you for your help. But I really doubt that `clx-xembed` sometimes using a `nil` value instead of an `unsigned-int` is causing the Slack window not showing up properly, because I haven't seen the "using nil value" error message since using `clx` 8381835 or earlier. The `nil` value problem might be another bug though.
Slack provides free account, so I'm wondering if it would be possible for you to register a free Slack account. And, yes, the Slack icon is on the tray, but the Slack window doesn't show up at the correct position with the correct size. Also, once you open up the Slack window, you won't be able to switch to other window, and your only choice is to exit Slack altogether.

**Comment by YorkZ** [comment]
Hi @admich, my apology I missed that you mentioned in your previous message that you used archlinux. So since you use archlinux, it's better to install Slack in AUR so that it will be managed by pacman. This is how I installed `Slack` on my archlinux:
```
  git clone https://aur.archlinux.org/slack-desktop.git
  cd slack-desktop
  makepkg -sic
```

**Comment by PuercoPop** [comment]
> I have the same problem but my experimentation have found that the problem is in clx and not in stumpwm.

@admich Commit bef2661 wouldn't introduce a bug, as all it does is change the compiler optimization settings, but reveal its presence. This would also explain why I only encounter the bug on one machine and not in the other. As one the one I encounter it I `restrict-compiler-policy` to a minimum of 1, for safety, and 3 for debug.

Thanks for the PR fixing the bug!

**Comment by OrionRandD** [comment]
Hi,
I am facing this stumptray unsigned byte32 error.
And stumptray does not show up anymore.
I installed stumpwm from github and also sbcl and quicklisp from there.
I am running the latest versions on my debian box
Could you make a step-by-step tuto on fixing this bug?
I have installed stumpwm about 4 times. Everything works fine, but stumptray
:(

**Comment by admich** [comment]
@OrionRandD 
The problem is the version of clx-xembed that is shipped with quicklisp.  
I made some little modifications and they are here: https://github.com/admich/clx-xembed
I made a PR to the main repo: https://github.com/laynor/clx-xembed but until it is not merged and a new quicklisp version is released (each month), you need to use the version of clx-xembed in my github.  Because you have installed stumpwm from github, I immagine that you know how to do it, anyway:
1. go to a directory where quicklisp/asdf can find the asdf-systems like `~/common-lisp` or `~/quicklisp/local-project`.
`$ cd ~/common-lisp`
2. clone my repow
`$ git clonehttps://github.com/admich/clx-xembed`
3. Try again stumpwm with stumptray
4. If you still have problems try to clean the common-lisp cache `~/.cache/common-lisp`

**Comment by OrionRandD** [comment]
On Tue, Sep 03, 2019 at 11:22:31PM -0700, admich wrote:

Many, many thanks for your fix!
It worked greatly. I just deleted the contents of

$HOME/quicklisp/dists/quicklisp/software/clx-xembed-20190307-git

and placed your "https://github.com/admich/clx-xembed" contents inside
that.

:)

------------------------

**Comment by admich** [comment]
@OrionRandD 
It's not necessary to delete 
$HOME/quicklisp/dists/quicklisp/software/clx-xembed-20190307-git 
contents and replace with mine. In this way in the future if you forgot what you have done you will think that you have the quicklisp version of clx-xembed

The directory
$HOME/quicklisp/local-project 
is just for this kind of things. You can clone my repo there and quickload will load my version.

**Comment by lxbarbosa** [comment]
@admich
Yes, it fixes the NIL issue. Thanks!

**Comment by YorkZ** [comment]
Just updated `clx`, `stump-wm`, `stump-wm-controb`, `Slack' and `clx-xembed` to the latest. Confirmed that everything works now. Thanks @admich.

**Comment by admich** [comment]
With november release of quicklisp the clx-xembed include my changes. So it is no more necessary to use a local version.

**Comment by lxbarbosa** [comment]
@admich 
At last, thanks!
