### ISSUE TITLE
stumpwm gaps broken in 19.11

### ISSUE THREAD

**Issue by brettgilio** [stumpwm/stumpwm-contrib#155]
StumpWM 19.11 release breaks swm-gaps on loading of the module indicating that it does not know how to reference the HEAD for manipulation.

**Comment by lepisma** [comment]
Hello, I am able to use gaps without issues. Running `version` shows `19.11.1-g73e6247 Compiled On Sat Dec 14 2019 16:08:35`.

Can you provide some more information and probably a way to reproduce this error?

**Comment by podiki** [comment]
Can't reproduce either, on latest git version `19.11-95...`
