### ISSUE TITLE
Suggestion: add tests to stumpwm-contrib using FiveAM or otherwise

### ISSUE THREAD

**Issue by equwal** [stumpwm/stumpwm-contrib#174]
I'm fond of [Fiveam](https://common-lisp.net/project/fiveam/docs/index.html) for the purpose of testing, and Travis for integration of pull requests. I think tests on the contribs could help ensure they are of the highest quality.

**Comment by dmb2** [comment]
contrib modules are a free-for-all I'm not implementing any testing requirements.  If you have an individual module and want to incorporate unit testing that is your prerogative, but not one that will be enforced at the contrib level.
