### ISSUE TITLE
swm-gaps can crash stumpwm with negative size windows

### ISSUE THREAD

**Issue by podiki** [stumpwm/stumpwm-contrib#178]
I've run into an occasional issue where stumpwm with gaps will crash trying to make a window of negative dimensions. This seems to happen when a program (e.g. Zoom) has a starting window/splash screen that is small.

This is the line that controls the size:
https://github.com/stumpwm/stumpwm-contrib/blob/7070f89919a794c725c01897957b7774f1c9b8eb/util/swm-gaps/swm-gaps.lisp#L65

I've confirmed this can be fixed by not allowing negative `:width` and `:height`. There are several ways we could fix this: minimum size, percentage size of screen, or don't do the gaps subtraction. Happy to make a pull request for whatever is the best way to handle this.

**Comment by lepisma** [comment]
I am not sure if I am thinking about all possible concerns but not doing gaps subtraction if negative feels fine. This is kind of a min size limit based on gap values right?

**Comment by podiki** [comment]
Yes, that's right. If the dimensions are less than the gaps, don't subtract (keep original size of window). Not sure if this is something that should go upstream, in that `set-window-geometry` doesn't catch negative values or fail gracefully. (while the X session stayed alive, I couldn't figure out how to get stump restarted.)

**Comment by podiki** [comment]
I can create a pull request that does the simple check of only doing the gaps subtraction if the result will be positive.

A related issue that I think would indirectly solve this (though this should still be fixed directly to prevent a crash) is that windows that do not fill their frame do not necessarily need to have gaps (there is already a gap). Seems like another easy fix, but I'm still learning what's what so I'd be happy to be pointed in the right direction (some check of window size versus it's frame).

**Comment by M4rkD** [comment]
For me this issue happens with a window that appears to be floating. Specifically the spinner when the Zoom client is loaded (https://zoom.us/download?os=linux).

I presume the fix should also check for floating windows.

**Comment by podiki** [comment]
> For me this issue happens with a window that appears to be floating. Specifically the spinner when the Zoom client is loaded (https://zoom.us/download?os=linux).
> 
> I presume the fix should also check for floating windows.

I'm not sure if Zoom creates floating windows by default, but I do know that Zoom when loading or other windows it pops up will crash due to this bug. Perhaps also related to #75? That might also be solved by not doing gaps when not needed, just gotta figure out the right thing to check and see if that helps.

**Comment by podiki** [comment]
Update: I'm also trying a check to see if the window fills the frame (minus the gap). This seems to solve these "transient" but not windows, and other dialog type windows with fixed size being shrunk by the gaps (#75?). I put this in the same spot as this fix, though I wonder if that really belongs elsewhere in checking if gaps should be applied, edge check...?

Combined, this fixes some annoyances with gaps and small windows, as well as the crash. I'll submit a pull request for review shortly.
