### ISSUE TITLE
ttf-fonts rendering issue

### ISSUE THREAD

**Issue by luka-n** [stumpwm/stumpwm-contrib#21]
To reproduce set a ttf font, and importantly, a **non-white fg color** (that is (set-fg-color "gray") say), and try the windows command, or any such list with highlights. Issue is I don't know where, but starts in the invert-rect function.

Attaching a screenshot illustrating the issue.

![render](https://cloud.githubusercontent.com/assets/7804277/5443915/6a41e4cc-84a6-11e4-88ce-6abadff8a2b6.png)

**Comment by dbjergaard** [comment]
Unfortunately this is not a stumpwm-contrib issue.  You should open an issue with the original author: https://github.com/filonenko-mikhail/clx-truetype/issues

**Comment by luka-n** [comment]
@dbjergaard why the reopen? I have a workaround for this, did a pr - https://github.com/stumpwm/stumpwm/pull/251
