### ISSUE TITLE
winner-mode shows message "Group dumped" on every window switch.

### ISSUE THREAD

**Issue by Junker** [stumpwm/stumpwm-contrib#242]
Every time i switch window winner-mode shows annoying message "Group dumped".
It can be fixed if use "(stumpwm::dump-to-file (stumpwm:dump-group (stumpwm:current-group)) file)" instead of command "stumpwm:dump-group-to-file" in dumper.lisp

fixed fun:
```lisp
(defun dump-group-to-file (&rest args)
  (declare (ignore args))
  (let* ((group-number (current-group-number)))
    (check-ids group-number *current-ids* *max-ids*)
    (stumpwm::dump-to-file (stumpwm:dump-group (stumpwm:current-group))
     (dump-name group-number (incf (gethash group-number *current-ids*))))
    (when (> (gethash group-number *current-ids*)
             (gethash group-number *max-ids*))
      (setf (gethash group-number *max-ids*)
            (gethash group-number *current-ids*)))))
```

**Comment by dmb2** [comment]
This is a very rare case where I don't mind using the internal symbol.  Maybe someday a verbose setting will be used and we can revert this.  I've updated it for now.
