### ISSUE TITLE
Move commands for spatial-groups

### ISSUE THREAD

**Issue by nameiwillforget** [stumpwm/stumpwm-contrib#277]
I really like the idea behind spatial-groups but there are no 
commands to allow you to move windows similar to
`gselect`. I thought I might be able to create such commands 
simply by replacing `gselect` in the relevant commands by
`gmove`, so doing this:

```
;; Move arrows between groups
(defcommand coordmove-left      () () (move-group-change -1  0 
0))
(defcommand coordmove-right     () () (move-group-change  1  0 
0))
(defcommand coordmove-up        () () (move-group-change  0  1 
0))
(defcommand coordmove-down      () () (move-group-change  0 -1 
0))
(defcommand coordmove-taskleft  () () (move-group-change  0  0 
-1))
(defcommand coordmove-taskright () () (move-group-change  0  0 
1))


(defun spatial-gmove (name)
  "Wrap gmove, preserve prior location for pop, and handle when 
  group is new"
  (when *spatial-banish-on-move* (banish))
  (setf *last-cursor* (group-name (current-group)))
  (gmove (group-name
             (or (spatial-find-group (current-screen) name)
               (gnew name)))))

(defun move-group-change (xo yo zo)
  "Navigate a 3d array of groups using x,y,z coordinates by 
  passing the offset of the change."
  (let* ((current-coords
          (mapcar #'parse-integer
                  (split-string (group-name (current-group)) 
                  ",")))
         (new-coords (mapcar #'+ current-coords (list xo yo zo)))
         (new-group-name (format nil "~{~a~^,~}" new-coords)) )

    (if (= 0 zo)

        ;; Not changing desktop, so just move by coordinates
        (spatial-gmove new-group-name)

        ;; Changing Z across desktops, RESTORE z-cursor for that 
        plane
        (let ((old-z (third current-coords))
              (new-z (third new-coords)))

          ;; Save current location for desktop so we can return to 
          same spot
          (if (assoc old-z *z-cursors*)
              (setf (cdr (assoc old-z *z-cursors*)) 
              (current-group))
              (push (cons old-z (current-group)) *z-cursors*))

             ;; Try to restore prior desktop location
          (let ((z-cursor (cdr (or (assoc new-z *z-cursors*) '(nil 
          . nil)))))
            (if z-cursor
                ;; Restore saved location
                (spatial-gmove (group-name z-cursor))
                ;; create new taskplane
                (spatial-gmove new-group-name)))))))
```

But when I try to use these commands, Stumpwm gives me the error 
that the generic function `group-windows` doesn't
accept inputs of the form of a tuple and stops working. I've 
looked at the command of `gmove` in `group.lisp` and it
refers to another command `move-window-to-group`, which is thus 
defined

```
(defun move-window-to-group (window to-group)
  (if (equalp to-group (window-group window))
      (message "That window is already in the group ~a." 
      (group-name to-group))
      (labels ((really-move-window (window to-group)
                 (unless (eq (window-group window) to-group)
                   (hide-window window)
                   ;; house keeping
                   (setf (group-windows (window-group window))
                         (remove window (group-windows 
                         (window-group window))))
                   (group-delete-window (window-group window) 
                   window)
                   (setf (window-group window) to-group
                         (window-number window) 
                         (find-free-window-number to-group))
                   (push window (group-windows to-group))
                   (xlib:change-property (window-xwin window) 
                   :_NET_WM_DESKTOP
                                         (list (netwm-group-id 
                                         to-group))
                                         :cardinal 32)
                   (group-add-window to-group window))))
        ;; When a modal window is moved, all the windows it 
        shadows must be moved
        ;; as well. When a shadowed window is moved, the modal 
        shadowing it must
        ;; be moved.
        (cond
          ((window-modal-p window)
           (mapc (lambda (w)
                   (really-move-window w to-group))
                 (append (list window) (shadows-of window))))
          ((modals-of window)
           (mapc (lambda (w)
                   (move-window-to-group w to-group))
                 (modals-of window)))
          (t
           (really-move-window window to-group))))))
```

I think the error appears because his clause

```
(setf (group-windows (window-group window))
      (remove window (group-windows 
      (window-group window))))
```
directly asks for the starting group position, which is then given as a tuple. `spatial-groups` contains a command to read the name of a group as a string:

```
(defun spatial-find-group (screen name)
  "Simple function to find group by string name"
  (find name (screen-groups screen) :key 'group-name :test 'string=))
```
This is what `spatial-gselect` sends to `gselect`:

```
(defun spatial-gselect (name)
  "Wrap gselect, preserve prior location for pop, and handle when group is new"
  (when *spatial-banish-on-move* (banish))
  (setf *last-cursor* (group-name (current-group)))
  (gselect (group-name
             (or (spatial-find-group (current-screen) name)
               (gnew name)))))
```
So I tried to create a variant of `move-window-to-group` that uses this command to instead of reading the starting group position directly and wrap it in a variant of gmove:

```
(defcommand sgmove (to-group) ((:group "To group: "))
"Move the current window to the specified group."
  (when (and to-group
             (current-window))
    (spatial-move-window-to-group (current-window) to-group)))



(defun spatial-move-window-to-group (window to-group)
  (if (equalp to-group (window-group window))
      (message "That window is already in the group ~a." (group-name to-group))
      (labels ((really-move-window (window to-group)
                 (unless (eq (window-group window) to-group)
                   (hide-window window)
                   ;; house keeping
                   (setf (group-windows (spatial-find-group (current-screen) name))
                         (remove window (group-windows (spatial-find-group (current-screen) name))))
                   (group-delete-window (spatial-find-group (current-screen) name) window)
                   (setf (window-group window) to-group
                         (window-number window) (find-free-window-number to-group))
                   (push window (group-windows to-group))
                   (xlib:change-property (window-xwin window) :_NET_WM_DESKTOP
                                         (list (netwm-group-id to-group))
                                         :cardinal 32)
                   (group-add-window to-group window))))
        ;; When a modal window is moved, all the windows it shadows must be moved
        ;; as well. When a shadowed window is moved, the modal shadowing it must
        ;; be moved.
        (cond
          ((window-modal-p window)
           (mapc (lambda (w)
                   (really-move-window w to-group))
                 (append (list window) (shadows-of window))))
          ((modals-of window)
           (mapc (lambda (w)
                   (move-window-to-group w to-group))
                 (modals-of window)))
          (t
           (really-move-window window to-group)))
	)))
```
However, if I try to use this, it tells me that `window-modal-p` is undefined, and if I comment out the modal and shadow conditions (while copying `(really-move-window window to-group)` out of the condition), I get the error message that `hide-window` is undefined. This even happens if I copy these commands into `group.lisp` in stumpwm itself, right next to `move-window-to-group`, which seems the only place `hide-window` appears.

I'd really like these functions and thought they would be easy to define, but I'm a bit out of my depth here. I'm not a programmer and I can only kind-of read lisp. Can somebody maybe help me here?

**Comment by rladams** [comment]
Try applying this diff:

diff -r 7958db8a20da spatial-groups.lisp
--- a/spatial-groups.lisp	Wed May 04 22:01:09 2022 +0200
+++ b/spatial-groups.lisp	Wed Sep 06 10:38:06 2023 +0200
@@ -144,6 +144,31 @@
 
 
 ;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
+;; Move windows between groups
+
+;; Move window between groups, no default keybinding.
+(defcommand coord-move-left      () () (coord-move-group-change -1  0  0))
+(defcommand coord-move-right     () () (coord-move-group-change  1  0  0))
+(defcommand coord-move-up        () () (coord-move-group-change  0  1  0))
+(defcommand coord-move-down      () () (coord-move-group-change  0 -1  0))
+(defcommand coord-move-taskleft  () () (coord-move-group-change  0  0 -1))
+(defcommand coord-move-taskright () () (coord-move-group-change  0  0  1))
+
+(defun coord-move-group-change (xo yo zo)
+  "Move current window to another group by coordinate offset"
+  (let* ((current-coords
+           (mapcar #'parse-integer
+             (split-string (group-name (current-group)) ",")))
+          (new-coords (mapcar #'+ current-coords (list xo yo zo)))
+          (new-group-name (format nil "~{~a~^,~}" new-coords))
+          (new-group (or (spatial-find-group (current-screen) new-group-name)
+                       (gnew new-group-name))))
+    ;; Move the current window to the new group, then move our view to that group
+    (gmove new-group)
+    (coord-group-change xo yo zo)))
+
+
+;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
 ;; Startup
 
 (defun spatial-startup ()

**Comment by nameiwillforget** [comment]
> Try applying this diff:
> 
> ```
> diff -r 7958db8a20da spatial-groups.lisp
> --- a/spatial-groups.lisp	Wed May 04 22:01:09 2022 +0200
> +++ b/spatial-groups.lisp	Wed Sep 06 10:38:06 2023 +0200
> @@ -144,6 +144,31 @@
>  
>  
>  ;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
> +;; Move windows between groups
> +
> +;; Move window between groups, no default keybinding.
> +(defcommand coord-move-left      () () (coord-move-group-change -1  0  0))
> +(defcommand coord-move-right     () () (coord-move-group-change  1  0  0))
> +(defcommand coord-move-up        () () (coord-move-group-change  0  1  0))
> +(defcommand coord-move-down      () () (coord-move-group-change  0 -1  0))
> +(defcommand coord-move-taskleft  () () (coord-move-group-change  0  0 -1))
> +(defcommand coord-move-taskright () () (coord-move-group-change  0  0  1))
> +
> +(defun coord-move-group-change (xo yo zo)
> +  "Move current window to another group by coordinate offset"
> +  (let* ((current-coords
> +           (mapcar #'parse-integer
> +             (split-string (group-name (current-group)) ",")))
> +          (new-coords (mapcar #'+ current-coords (list xo yo zo)))
> +          (new-group-name (format nil "~{~a~^,~}" new-coords))
> +          (new-group (or (spatial-find-group (current-screen) new-group-name)
> +                       (gnew new-group-name))))
> +    ;; Move the current window to the new group, then move our view to that group
> +    (gmove new-group)
> +    (coord-group-change xo yo zo)))
> +
> +
> +;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
>  ;; Startup
>  
>  (defun spatial-startup ()
> ```
> 
> You'll have to bind keys to the new coord-move-* commands, or call them as commands.

Thanks! I tried applying the diff using `git apply` in my modules directory and the spatial-groups sub-directory but git said `corrupt patch at line 6`, and `corrupt patch at line 5` when I deleted line 6. I then tried to apply the patch manually by copying the relevant portion at the specified place, right under the line of semicolons, then reloading my rc, but stumpwm says "The function SPATIAL-GROUPS::CURRENT-COORDS is undefined". This persisted after I did a soft and hard restart of stumpwm and when I tried placing the code at other places in the file, like right next to `coord-group-change`. I really don't get it. The beginning is exactly the same as `coord-group-change`, yet it doesn't compain about that function. Is there something I have to add to `package-lisp` or some other file, or do I have to recompile something?

**Comment by rladams** [comment]
You should have been able to save the grey box content to a file, and feed that to the patch command, but try pasting this in.

```
;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
;; Move windows between groups

;; Move window between groups, no default keybinding.
(defcommand coord-move-left      () () (coord-move-group-change -1  0  0))
(defcommand coord-move-right     () () (coord-move-group-change  1  0  0))
(defcommand coord-move-up        () () (coord-move-group-change  0  1  0))
(defcommand coord-move-down      () () (coord-move-group-change  0 -1  0))
(defcommand coord-move-taskleft  () () (coord-move-group-change  0  0 -1))
(defcommand coord-move-taskright () () (coord-move-group-change  0  0  1))

(defun coord-move-group-change (xo yo zo)
  "Move current window to another group by coordinate offset"
  (let* ((current-coords
           (mapcar #'parse-integer
             (split-string (group-name (current-group)) ",")))
          (new-coords (mapcar #'+ current-coords (list xo yo zo)))
          (new-group-name (format nil "~{~a~^,~}" new-coords))
          (new-group (or (spatial-find-group (current-screen) new-group-name)
                       (gnew new-group-name))))
    ;; Move the current window to the new group, then move our view to that group
    (gmove new-group)
    (coord-group-change xo yo zo)))

```

**Comment by nameiwillforget** [comment]
That works! Thanks so much!
