### ISSUE TITLE
cant get productivity do what I want

### ISSUE THREAD

**Issue by spiderbit** [stumpwm/stumpwm-contrib#34]
I put following in my config:

``` lisp
(add-to-load-path "~/.stumpwm.d/contrib/util/productivity")
(load-module "productivity")
(define-key *top-map* (kbd "S-Menu") "productivity-mode-toggle")

(setf *productivity-keys*
      '(("C-Menu"   *root-map*)
        ("Menu"   "app-send-key-menu")
    ))
```

the problem is when I press S-Menu it says correctly "Break time" or "Get to Work" but it changes nothing. My Menu + y command (Menu is my prefix key) always calls  always "window-list" I thought in Workmode that should not happen.

here the setup of the window list and prefix key:

``` lisp
(set-prefix-key (kbd "Menu"))
(define-key *root-map* (kbd "y") "windowlist")
```

Am I understanding it wrong how to set it up or what it should do? ignore basicly everything till I press S-Menu again?

**Comment by dbjergaard** [comment]
Sorry, I didn't see this til now.  These (older) modules aren't very well supported. Did you figure out how to make it work?

**Comment by spiderbit** [comment]
no, I kind of worked around it and not using that modul anymore.

basicly in stumpwm I press my prefix key twice to send the command to the app if that makes sence or relates at all to the productivity mode something like that:

(define-key *top-map* (kbd "S-Menu") "productivity-on")
(define-key *top-map* (kbd "C-Menu") "productivity-off")

(defcommand productivity-on () ()
  (set-prefix-key (kbd "Menu")))

(defcommand productivity-off () ()
  (set-prefix-key (kbd "XF86Launch8")))

(set-prefix-key (kbd "Menu")))
(define-key *root-map* (kbd "Menu") "app-send-key-menu")

(defcommand app-send-key-menu () ()
  (let ((wclass (window-class(current-window))))
    (when (string-equal wclass "Emacs")
      (send-meta-key (current-screen) (kbd "Menu")))
    (when (string-equal wclass "Conkeror")
      (send-meta-key (current-screen) (kbd "F8")))))

I use here for F8 because conkeror has hardcoded Menu key function that you cant overwrite but its the key I want to press :)

I dont know if that makes to much sense basicly I had this productivity code because on my laptop keyboard or before I understood how to create this sub-keymap.

Its a whlie that I changed that last time so I hope it makes still some kind of sense, I play more with exwm lately so I am not to much into stumpwm config right now :)
