### ISSUE TITLE
amixer module also changes volume when toggling mute state on/off

### ISSUE THREAD

**Issue by kisp** [stumpwm/stumpwm-contrib#40]
It simply would be nice if toggling did not have other side effects.

The side effect was introduced in 10d52216503992664327bca90d6bed0ac1401837 as a workaround. Is it still needed?

I am running ```amixer version 1.0.29``` and toggling here works perfectly.

**Comment by jorams** [comment]
I'd like to see this closed. @juszczakn can you confirm this workaround isn't needed (anymore)?

**Comment by juszczakn** [comment]
@jorams I found the workaround here: http://askubuntu.com/questions/65764/how-do-i-toggle-sound-with-amixer

With the version of amixer I was using it was the only way to get the toggle working. Running Ubuntu 14.04 with amixer v1.0.27.2 seems like it's no longer needed, so I say remove it.

**Comment by jorams** [comment]
:+1: Thanks, reverted.
