### ISSUE TITLE
Error In Command 'stumptray': The value NIL is not of type MODE-LINE.

### ISSUE THREAD

**Issue by mashdot** [stumpwm/stumpwm-contrib#43]
I just discovered the stumptray module, yet unable to get it to run.

The above error is reported whenever I run the command "stumptray".

Any ideas?

**Comment by jorams** [comment]
@mashdot Do you have the modeline enabled when you run it?

**Comment by mashdot** [comment]
Yeah, enabled. I also tried to disabling and enabling the mode-line.

Also just tried running "stumptray-toggle-hidden-icons-visibility" and saw the following...

> Error In Command 'stumptray-toggle-hidden-icons-visibility': The value NIL is not of type STUMPTRAY::TRAY.

**Comment by dbjergaard** [comment]
Here's my invocation:
(load-module "stumptray")

(mapc (lambda (head)
	(toggle-mode-line (current-screen) head)) 
      (screen-heads (current-screen)))
(run-commands "stumptray")

**Comment by mashdot** [comment]
OK really not sure what has changed, but it is now working after I had to reboot. :(

I just need to work out how to add some left padding since the icons overlap the mode-line text.

Thanks everyone for their help.
