### ISSUE TITLE
Duplicated keybinding in mpd module

### ISSUE THREAD

**Issue by nakiakira** [stumpwm/stumpwm-contrib#46]
Both command use "S"...
```<978> (kbd "S") "mpd-current-song"```
```<993> (kbd "S") '*mpd-search-map*```
...so please change one it, eg.: 
```<978> (kbd "i") "mpd-current-song" ;like info```

**Comment by jorams** [comment]
Good idea. Since the current keymap doesn't allow access to the current song, so I don't think anyone would disagree with the change.
