### ISSUE TITLE
swm-gaps not working?

### ISSUE THREAD

**Issue by ahmed-shariff** [stumpwm/stumpwm-contrib#77]
I followed the instructions, and yet there is nothing happening. There is no gaps even if i evaluate something like :
`(setf swm-gaps:*outer-gaps-size* 200)`

Thanx in advance

**Comment by jorams** [comment]
Have you called the command `toggle-gaps`?

**Comment by ahmed-shariff** [comment]
my bad.
Thank you very much @jorams
