### ISSUE TITLE
stumptray - module not found

### ISSUE THREAD

**Issue by voobscout** [stumpwm/stumpwm-contrib#79]
very easy to repro:

```lisp
;; asdf system loads perfectly fine
(ql:quickload "stumptray")
;; stumpwm doesn't know about that module
(load-module "stumptray")
```

**Comment by dbjergaard** [comment]
I need more information as I use (load-module "stumptray") in my rc file without issues.

Can you do the following from slime?
```lisp
; SLIME 2016-04-19
CL-USER> (in-package :stumpwm)
#<PACKAGE "STUMPWM">
STUMPWM> (find "stumptray" *load-path* :test (lambda (a b) (search a (namestring b))))
"/home/dave/.stumpwm.d/modules/util/stumptray/"
STUMPWM> (find "stumptray" asdf:*central-registry* :test (lambda (a b) (search a (namestring b))))
"/home/dave/.stumpwm.d/modules/util/stumptray/"
STUMPWM> (find "stumptray" (list-modules) :test 'equal)
"stumptray"
```

**Comment by voobscout** [comment]
This happens even while stumptray works, weird...
```lisp
STUMPWM> (in-package :stumpwm)
#<PACKAGE "STUMPWM">
STUMPWM> (find "stumptray" *load-path* :test (lambda (a b) (search a (namestring b))))
NIL
STUMPWM> (find "stumptray" asdf:*central-registry* :test (lambda (a b) (search a (namestring b))))
NIL
STUMPWM> (find "stumptray" (list-modules) :test 'equal)
NIL
```

Aside from that weirdness, my stumptray actually works, rather it started working again after ```rm -rf ~/.cache/common-lisp```

I no longer think it is a bug with stumptray or stumpwm, i am chucking it up to my lisp illiteracy and some setts in env. A 'clean' install works as expected.

It'd be nice to hear thoughts on why stumptray works and is not being detected in slime, but other then that this issue should be closed.
