### ISSUE TITLE
Export swm-gaps:*gaps-on* to be able to toggle gaps in stumpwmrc safely

### ISSUE THREAD

**Issue by john2x** [stumpwm/stumpwm-contrib#87]
I'm trying to do something like the following in my config

```
(if (not swm-gaps:*gaps-on*)
  (swm-gaps:toggle-gaps))
```
to avoid toggling gaps when reloading my config. But it doesn't work because `*gaps-on*` isn't exported.

**Comment by PuercoPop** [comment]
Thanks for submitting the issue
