### ISSUE TITLE
Update app-menu.

### ISSUE THREAD

**Issue by kostafey** [stumpwm/stumpwm-contrib#94]
Hi all! 
What's wrong with `app-menu` pull request (https://github.com/stumpwm/stumpwm-contrib/pull/92)?
Can I improve it?

**Comment by dbjergaard** [comment]
Hi, the PR was opened right before my holiday break.  I don't typically come to the contrib repo unless I'm reading a PR.  Sorry for the delay. In the future, keeping the discussion of PRs on the PR page helps keep everything unified.  

Sorry again for the delay in merging.  All of us do this part-time, and I've been particularly busy lately.
